version: 2

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        command: mysqld --innodb-file-format=Barracuda --innodb_file_per_table=true --innodb-large-prefix=true
    steps:
      - checkout
      - run: bundle -v
      - run: bundle check || bundle install --clean
      - run: bin/rails db:create
      - run: bin/rails db:schema:load --trace
      - run: bundle exec rspec --profile 10 --format progress
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
