default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: test_circleci_development

test:
  <<: *default
  database: test_circleci_development
  password:
production:
  <<: *default
  database: test_circleci_development
